#:kivy 2.1.0
#:import random random
#:import os os

<AnimalMaster@HoverBehavior+Image>:
    on_enter: self.parent.callback()
    size: app.TAMANO_IMAGENES, app.TAMANO_IMAGENES
    anim_delay: app.VELOCIDAD_ANIMACION
    #pos: random.randint(50, 950), random.randint(50, 450)
    pos: random.randint(app.TAMANO_IMAGENES, app.MARGEN_ANCHO), random.randint(app.TAMANO_IMAGENES, app.MARGEN_ALTO)

<Animal>:
    AnimalMaster:
        source: root.fuente
        id: animal